import { lazy } from "react";
// import AddStage from "./views/Stages/AddStage.jsx";

const AddStage = lazy(() => import("./views/Stages/AddStage.jsx"));
const Inbox = lazy(() => import("./views/Inbox/inbox.jsx"));
const Language = lazy(() => import("./views/Language/Language.jsx"));
const AddLanguage = lazy(() => import("./views/Language/AddLanguage.jsx"));
const BannedEmails = lazy(() => import("./views/BannedEmails/Emails.jsx"));
const AddBannedEmails = lazy(() => import("./views/BannedEmails/AddEmail.jsx"));
const Setting = lazy(() => import("./views/Setting/Setting.jsx"));
const Banner = lazy(() => import("./views/Setting/Banner.jsx"));
const SliderImages = lazy(() => import("./views/SliderImage/SliderImages.jsx"));
const Communities = lazy(() => import("./views/Communities/Communities.jsx"));
const ArchivedComunities = lazy(() =>
  import("./views/Communities/ArchivedCommunities.jsx"),
);
const AddCommunity = lazy(() => import("./views/Communities/AddCommunity.jsx"));
const Moderators = lazy(() => import("./views/Moderators/Moderators.jsx"));
const AddModerator = lazy(() => import("./views/Moderators/AddModerator.jsx"));
const Members = lazy(() => import("./views/Communities/Members.jsx"));
const PendingPosts = lazy(() => import("./views/Communities/PendingPosts.jsx"));
const PendingRequests = lazy(() =>
  import("./views/Communities/PendingRequests.jsx"),
);
const Ads = lazy(() => import("./views/Ads/Ads.jsx"));
const AddAd = lazy(() => import("./views/Ads/AddAd.jsx"));
const FeaturedPost = lazy(() =>
  import("./views/FeaturedPost/FeaturedPost.jsx"),
);
const FeaturedCaseStudies = lazy(() =>
  import("./views/CaseStudies/FeaturedCaseStudies.jsx"),
);
const PendingCaseStudies = lazy(() =>
  import("./views/CaseStudies/PendingCaseStudies.jsx"),
);
const CaseStudies = lazy(() => import("./views/CaseStudies/CaseStudies.jsx"));
const AddFeaturedPost = lazy(() =>
  import("./views/FeaturedPost/AddFeaturedPost.jsx"),
);
const Products = lazy(() => import("./views/Products/Products.jsx"));
const Stages = lazy(() => import("./views/Stages/Stages.jsx"));
const Users = lazy(() => import("./views/Users.jsx"));
const AddAboutUsPoint = lazy(() =>
  import("./views/AboutUs/AddAboutUsPoint.jsx"),
);
const Events = lazy(() => import("./views/Event/Event.jsx"));
const PendingApprovalEvents = lazy(() =>
  import("./views/Event/PendingApprovalEvent.jsx"),
);
const FeaturedEvents = lazy(() => import("./views/Event/FeaturedEvents.jsx"));
const PendingApprovalFeaturedEvents = lazy(() =>
  import("./views/Event/PendingApprovalFeaturedEvents.jsx"),
);
const Reported = lazy(() => import("./views/Reported/Reported.jsx"));
const Links = lazy(() => import("./views/Links/Links.jsx"));
const AddLink = lazy(() => import("./views/Links/AddLink.jsx"));
const Analytics = lazy(() => import("./views/analytics/Analytic.jsx"));
const TopUsers = lazy(() => import("./views/analytics/TopUser"));
const TopPosts = lazy(() => import("./views/analytics/TopPosts.jsx"));
const SiteAnalytic = lazy(() => import("./views/analytics/Site"));
const CommunityGA = lazy(() => import("./views/analytics/CommunityGA"));
const Award = lazy(() => import("./views/Awards/NewEdit"));
const AwardList = lazy(() => import("./views/Awards/List"));

const routes = [
  {
    hasChildren: false,
    count: 0,
    children: [
      {
        hasChildren: true,
        path: "/posts",
        name: "Top posts",
        icon: "nc-icon nc-tile-56",
        layout: "/admin",
        component: TopPosts,
      },
      {
        hasChildren: true,
        path: "/topusers",
        name: "Top Users",
        icon: "nc-icon nc-tile-56",
        layout: "/admin",
        component: TopUsers,
      },
      {
        hasChildren: true,
        path: "/analytics",
        name: "Community",
        icon: "nc-icon nc-tile-56",
        layout: "/admin",
        component: Analytics,
      },
      {
        hasChildren: true,
        path: "/site",
        name: "Site",
        icon: "nc-icon nc-tile-56",
        layout: "/admin",
        component: SiteAnalytic,
      },
      {
        hasChildren: true,
        path: "/comga",
        name: "Community GA",
        icon: "nc-icon nc-tile-56",
        layout: "/admin",
        component: CommunityGA,
      },
    ],
    path: "/analytics",
    name: "Analytics",
    icon: "nc-icon nc-tile-56",
    layout: "/admin",
    component: Analytics,
  },
  {
    hasChildren: true,
    path: "/posts",
    name: "Top posts",
    icon: "nc-icon nc-tile-56",
    layout: "/admin",
    component: TopPosts,
  },
  {
    hasChildren: true,
    path: "/topusers",
    name: "Top Users",
    icon: "nc-icon nc-tile-56",
    layout: "/admin",
    component: TopUsers,
  },
  {
    hasChildren: true,
    count: 0,
    path: "/products",
    name: "Products",
    icon: "nc-icon nc-tile-56",
    component: Products,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/users",
    name: "Users",
    icon: "nc-icon nc-tile-56",
    component: Users,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/about-us/point/create-update",
    name: "About Us Point",
    icon: "nc-icon nc-tile-56",
    component: AddAboutUsPoint,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/links/create-update",
    name: "Add Link",
    icon: "nc-icon nc-tile-56",
    component: AddLink,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/links",
    name: "Links",
    icon: "nc-icon nc-tile-56",
    component: Links,
    layout: "/admin",
  },
  // { hasChildren: true,
  //     path: "/about-us",
  //     name: "About Us",
  //     icon: "nc-icon nc-tile-56",
  //     component: AboutUs,
  //     layout: "/admin",
  // },
  {
    hasChildren: true,
    count: 0,
    path: "/slider-images",
    name: "Slider Images",
    icon: "nc-icon nc-tile-56",
    component: SliderImages,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/ads/create-update",
    name: "Add Ad",
    component: AddAd,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/ads",
    name: "Ads",
    icon: "nc-icon nc-tile-56",
    component: Ads,
    layout: "/admin",
  },
  {
    hasChildren: false,
    count: 0,
    path: "/stages",
    name: "Stages",
    icon: "nc-icon nc-tile-56",
    // component: Stages,
    layout: "/admin",
    children: [
      {
        hasChildren: false,
        path: "/stages",
        name: "Stages",
        icon: "nc-icon nc-tile-56",
        layout: "/admin",
        component: Stages,
      },
      {
        hasChildren: false,
        path: "/stages/add",
        name: "Add Stage",
        icon: "nc-icon nc-tile-56",
        layout: "/admin",
        component: AddStage,
      },
    ],
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/featured-case-studies",
    name: "Featured Case Studies",
    component: FeaturedCaseStudies,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/pending-case-studies",
    name: "Pending Case Studies",
    component: PendingCaseStudies,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/case-studies",
    name: "Case Studies",
    icon: "nc-icon nc-tile-56",
    component: CaseStudies,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/featured-events/pending-approval",
    name: "Pending Approval Featured Events",
    icon: "nc-icon nc-tile-56",
    component: PendingApprovalFeaturedEvents,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/reported-events",
    name: "Reported",
    icon: "nc-icon nc-tile-56",
    component: Reported,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/featured-events",
    name: "Featured Events",
    icon: "nc-icon nc-tile-56",
    component: FeaturedEvents,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/events/pending-approval",
    name: "Pending Approval Events",
    icon: "nc-icon nc-tile-56",
    component: PendingApprovalEvents,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/events",
    name: "Events",
    icon: "nc-icon nc-tile-56",
    component: Events,
    layout: "/admin",
  },
  // { hasChildren: true,
  //     count: 0,
  //     path: "/inbox",
  //     name: "Inbox",
  //     icon: "nc-icon nc-tile-56",
  //     component: Inbox,
  //     layout: "/admin",
  // },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/featured-post/create-update",
    name: "Add Featured Post",
    component: AddFeaturedPost,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/featured-post",
    name: "Featured Post",
    icon: "nc-icon nc-tile-56",
    component: FeaturedPost,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/pending-posts/:id",
    name: "Pending Requests",
    icon: "nc-icon nc-single-02",
    component: PendingPosts,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/pending-request/:id",
    name: "Pending Requests",
    icon: "nc-icon nc-single-02",
    component: PendingRequests,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/moderators/create-update/:id",
    name: "Add Moderator",
    icon: "nc-icon nc-single-02",
    component: AddModerator,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/members/:id",
    name: "Members",
    icon: "nc-icon nc-single-02",
    component: Members,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/moderators",
    name: "Moderators",
    icon: "nc-icon nc-single-02",
    component: Moderators,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/communities/archived",
    name: "Communities",
    icon: "nc-icon nc-single-02",
    component: ArchivedComunities,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/communities/create-update",
    name: "Add Community",
    component: AddCommunity,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/communities",
    name: "Communities",
    icon: "nc-icon nc-single-02",
    component: Communities,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/language/create-update",
    name: "Add Language",
    icon: "nc-icon nc-tile-56",
    component: AddLanguage,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/language",
    name: "Languages",
    icon: "nc-icon nc-tile-56",
    component: Language,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/banned-email/create-update",
    name: "Add Banned Email",
    icon: "nc-icon nc-tile-56",
    component: AddBannedEmails,
    layout: "/admin",
  },

  {
    hasChildren: true,
    count: 0,
    path: "/banned-email",
    name: "Banned Email",
    icon: "nc-icon nc-tile-56",
    component: BannedEmails,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/banner",
    name: "Banner",
    icon: "nc-icon nc-tile-56",
    component: Banner,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/setting",
    name: "Setting",
    icon: "nc-icon nc-tile-56",
    component: Setting,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/awards",
    name: "Awards",
    icon: "nc-icon nc-tile-56",
    component: AwardList,
    layout: "/admin",
  },
  {
    hasChildren: true,
    inSidebar: false,
    count: 0,
    path: "/award/create-update",
    name: "Add Awards",
    icon: "nc-icon nc-tile-56",
    component: Award,
    layout: "/admin",
  },
];

const actualRoutes = [
  {
    hasChildren: true,
    count: 0,
    path: "/posts",
    name: "Top posts",
    icon: "nc-icon nc-tile-56",
    layout: "/admin",
    component: TopPosts,
  },
  {
    hasChildren: true,
    count: 0,
    path: "/topusers",
    name: "Top Users",
    icon: "nc-icon nc-tile-56",
    layout: "/admin",
    component: TopUsers,
  },
  {
    hasChildren: true,
    count: 0,
    path: "/analytics",
    name: "Community",
    icon: "nc-icon nc-tile-56",
    layout: "/admin",
    component: Analytics,
  },
  {
    hasChildren: true,
    count: 0,
    path: "/site",
    name: "Site",
    icon: "nc-icon nc-tile-56",
    layout: "/admin",
    component: SiteAnalytic,
  },
  {
    hasChildren: true,
    count: 0,
    path: "/comga",
    name: "Community GA",
    icon: "nc-icon nc-tile-56",
    layout: "/admin",
    component: CommunityGA,
  },
  {
    hasChildren: true,
    count: 0,
    path: "/products",
    name: "Products",
    icon: "nc-icon nc-tile-56",
    component: Products,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/users",
    name: "Users",
    icon: "nc-icon nc-tile-56",
    component: Users,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/about-us/point/create-update",
    name: "About Us Point",
    icon: "nc-icon nc-tile-56",
    component: AddAboutUsPoint,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/links/create-update",
    name: "Add Link",
    icon: "nc-icon nc-tile-56",
    component: AddLink,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/links",
    name: "Links",
    icon: "nc-icon nc-tile-56",
    component: Links,
    layout: "/admin",
  },
  // { hasChildren: true,
  //     path: "/about-us",
  //     name: "About Us",
  //     icon: "nc-icon nc-tile-56",
  //     component: AboutUs,
  //     layout: "/admin",
  // },
  {
    hasChildren: true,
    count: 0,
    path: "/slider-images",
    name: "Slider Images",
    icon: "nc-icon nc-tile-56",
    component: SliderImages,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/ads/create-update",
    name: "Add Ad",
    component: AddAd,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/ads",
    name: "Ads",
    icon: "nc-icon nc-tile-56",
    component: Ads,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/stages",
    name: "Stages",
    icon: "nc-icon nc-tile-56",
    component: Stages,
    layout: "/admin",
  },
  {
    hasChildren: true,

    count: 0,
    inSidebar: false,
    path: "/featured-case-studies",
    name: "Featured Case Studies",
    component: FeaturedCaseStudies,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/pending-case-studies",
    name: "Pending Case Studies",
    component: PendingCaseStudies,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/case-studies",
    name: "Case Studies",
    icon: "nc-icon nc-tile-56",
    component: CaseStudies,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/featured-events/pending-approval",
    name: "Pending Approval Featured Events",
    icon: "nc-icon nc-tile-56",
    component: PendingApprovalFeaturedEvents,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/reported-events",
    name: "Reported",
    icon: "nc-icon nc-tile-56",
    component: Reported,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/featured-events",
    name: "Featured Events",
    icon: "nc-icon nc-tile-56",
    component: FeaturedEvents,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/events/pending-approval",
    name: "Pending Approval Events",
    icon: "nc-icon nc-tile-56",
    component: PendingApprovalEvents,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/events",
    name: "Events",
    icon: "nc-icon nc-tile-56",
    component: Events,
    layout: "/admin",
  },
  // { hasChildren: true,
  //     count: 0,
  //     path: "/inbox",
  //     name: "Inbox",
  //     icon: "nc-icon nc-tile-56",
  //     component: Inbox,
  //     layout: "/admin",
  // },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/featured-post/create-update",
    name: "Add Featured Post",
    component: AddFeaturedPost,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/featured-post",
    name: "Featured Post",
    icon: "nc-icon nc-tile-56",
    component: FeaturedPost,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/pending-posts/:id",
    name: "Pending Requests",
    icon: "nc-icon nc-single-02",
    component: PendingPosts,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/pending-request/:id",
    name: "Pending Requests",
    icon: "nc-icon nc-single-02",
    component: PendingRequests,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/moderators/create-update/:id",
    name: "Add Moderator",
    icon: "nc-icon nc-single-02",
    component: AddModerator,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/members/:id",
    name: "Members",
    icon: "nc-icon nc-single-02",
    component: Members,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/moderators",
    name: "Moderators",
    icon: "nc-icon nc-single-02",
    component: Moderators,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/communities/archived",
    name: "Communities",
    icon: "nc-icon nc-single-02",
    component: ArchivedComunities,
    layout: "/admin",
  },
  {
    hasChildren: true,
    inSidebar: false,
    count: 0,
    path: "/communities/create-update",
    name: "Add Community",
    component: AddCommunity,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/communities",
    name: "Communities",
    icon: "nc-icon nc-single-02",
    component: Communities,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/awards",
    name: "Awards",
    icon: "nc-icon nc-tile-56",
    component: AwardList,
    layout: "/admin",
  },
  {
    hasChildren: true,
    inSidebar: false,

    count: 0,
    path: "/award/create-update",
    name: "Add Awards",
    icon: "nc-icon nc-tile-56",
    component: Award,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/language/create-update",
    name: "Add Language",
    icon: "nc-icon nc-tile-56",
    component: AddLanguage,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/language",
    name: "Languages",
    icon: "nc-icon nc-tile-56",
    component: Language,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    inSidebar: false,
    path: "/banned-email/create-update",
    name: "Add Banned Email",
    icon: "nc-icon nc-tile-56",
    component: AddBannedEmails,
    layout: "/admin",
  },

  {
    hasChildren: true,
    count: 0,
    path: "/banned-email",
    name: "Banned Email",
    icon: "nc-icon nc-tile-56",
    component: BannedEmails,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/banner",
    name: "Banner",
    icon: "nc-icon nc-tile-56",
    component: Banner,
    layout: "/admin",
  },
  {
    hasChildren: true,
    count: 0,
    path: "/setting",
    name: "Setting",
    icon: "nc-icon nc-tile-56",
    component: Setting,
    layout: "/admin",
  },
];

export default routes;
export { actualRoutes };
